{
 "title": "Nomios Dashboard By Source",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource1", "query": "prometheus" },
   {
    "name": "min_interval",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Connector uptime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "absent(absent(source_metrics_counter_total{group=\"mysql\", type=\"event_parsed\", hyperloop=\"catalogdb-connector\"}))",
     "legendFormat": "catalogdb-connector"
    }
   ]
  },
  {
   "title": "Binlog events per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(increase(source_metrics_counter_total{group=\"mysql\", type=\"event_parsed\"}[1m])/60) by (hyperloop, type)",
     "legendFormat": "{{ hyperloop }} - {{ type }}"
    },
    {
     "expr": "sum(increase(source_metrics_counter_total{group=\"mysql\", type=\"event_filtered\"}[1m])/60) by (hyperloop, type)",
     "legendFormat": "{{ hyperloop }} - {{ type }}"
    },
    {
     "expr": "sum(increase(source_metrics_counter_total{group=\"mysql\", type=\"event_mapped\"}[1m])/60) by (hyperloop, type)",
     "legendFormat": "{{ hyperloop }} - {{ type }}"
    }
   ]
  },
  {
   "title": "Event published",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(increase(publisher_metrics_counter_total{type=\"publish_success\"}[1m])/60) by (group)",
     "legendFormat": "{{ group }}"
    }
   ]
  },
  {
   "title": "Payload size (Kbs)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(publisher_metrics_histogram_sum{type=\"payload_size\"}[1m]) / 1024 / rate(publisher_metrics_histogram_count{type=\"payload_size\"}[1m])) by (group)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Pool buffer size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pool_metrics_histogram_sum{type=\"buffer_size\"}[1m]) / rate(pool_metrics_histogram_count{type=\"buffer_size\"}[1m])) by (hyperloop, group)",
     "legendFormat": "{{ hyperloop }}: {{ group }}"
    }
   ]
  },
  {
   "title": "Seconds behind master",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(rate(source_metrics_histogram_sum{type=\"milliseconds_behind_source\"}[1m]) / rate(source_metrics_histogram_count{type=\"milliseconds_behind_source\"}[1m])) by(hyperloop)",
     "legendFormat": "{{hyperloop}}"
    }
   ]
  },
  {
   "title": "Number of publish events per batch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(publisher_metrics_histogram_sum{type=\"publish_batch_size\"}[1m]) / rate(publisher_metrics_histogram_count{type=\"publish_batch_size\"}[1m])) by (hyperloop)",
     "legendFormat": "{{ hyperloop }}"
    }
   ]
  },
  {
   "title": "Publish time per batch (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(publisher_metrics_histogram_sum{type=\"publish_time\"}[1m]) / rate(publisher_metrics_histogram_count{type=\"publish_time\"}[1m]) / 1000) by (hyperloop)",
     "legendFormat": "{{ hyperloop }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{app=\"nomios-kafka-connect\"}",
     "legendFormat": "{{kubernetes_pod_name}} {{pool}}"
    }
   ]
  },
  {
   "title": "CPU Utilization ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=\"nomios-kafka-connect\"}[60s]) * 100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}