CREATE TABLE `default_value` (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  A VARCHAR(10) NULL DEFAULT "a",
  B DECIMAL(4, 3) NULL DEFAULT 2.321,
  C INT(10) NULL DEFAULT 999999,
  D TINYINT NULL DEFAULT 0,
  E TINYINT UNSIGNED NULL DEFAULT 1,
  F TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO `default_value`(A, B, C, D, E, F) VALUES (NULL, NULL, NULL, NULL, NULL, NULL);
